version: '2'

volumes:
  ruby2.6-gem-cache:
    external: true

services:
  dev:
    image: ruby:2.6.3@sha256:a29bfc3b57e4f2cce2970611dd3a6310a316963d80b2bd40bb8698ea234144ab
    volumes:
      - .:/app
      - ruby2.6-gem-cache:/usr/local/bundle
    environment:
      AWS_SESSION_TOKEN:
      AWS_DEFAULT_REGION:
      AWS_SECRET_ACCESS_KEY:
      AWS_ACCESS_KEY_ID:
      AWS_SECURITY_TOKEN:
    working_dir: /app
    entrypoint: ["/bin/bash", "-c"]
